- hosts: localhost

  vars:
      digital_ocean_token: dop_v1_d8c45828aa0eccb038638b75628bbbb5d978446b3be4994604d66736f31f7422
      droplet_size: s-1vcpu-1gb
      droplet_region: nyc1
      droplet_image: CentOS-7-x64

      droplets:
      - JonesC-202301-WP1
      - JonesC-202301-WP2

  tasks:
    - name: "add public ssh key to digitalocean account"
      digital_ocean_sshkey:
        name: "do_key"
        oauth_token: "{{digital_ocean_token}}"
        ssh_pub_key: "{{lookup('file','~/.ssh/id_rsa.pub')}}"
        state: present
      register: sshkey_result

    - name: create a new droplet assigning the key
      digital_ocean_droplet:
        name: "{{item}}"
        oauth_token: "{{digital_ocean_token}}"
        size: "{{droplet_size}}"
        region: "{{droplet_region}}"
        image: "{{droplet_image}}"
        wait_timeout: 600
        unique_name: yes
        ssh_keys: ["{{sshkey_result.data.ssh_key.id}}"]
        state: present
      with_items: "{{droplets}}"
      register: droplet_results

    - name: save ip and hostname to local host file /etc/ansible/hosts
      add_host:
        path: /etc/ansible/hosts
        name: "{{item.data.ip_address}}"
        group: droplets
      with_items: "{{droplet_results.results}}"

    - pause:
        seconds: 60

- hosts: droplets
  tasks:

          - name: Install LAMP
            yum:
              name:
                - httpd
                - mariadb-server
                - php
                - nano
                - wget
                - rsync
                - firewalld
                - git-all

          - name: Install epel-release
            yum:
              name: epel-release
              state: latest
              update_cache: yes

          - name: Update
            yum:
              name: '*'
              state: present

          - name: Firewall HTTP Configuration
            firewalld:
              zone: public
              service: http
              permanent: yes
              state: enabled

          - name: Firewall SSH Configuration
            firewalld:
              zone: public
              service: ssh
              permanent: yes
              state: enabled

          - name: Reload Firewall
            service:
              name: firewalld
              state: reloaded

          - name: Start and Enable Apache
            service:
              name: httpd
              enabled: true
              state: started

          - name: Install MariaDB
            yum:
              name: mariadb-server
              state: latest

          - name: MariaDB Status Check
            service:
              name: mariadb
              state: started

          - name: Install Python
            yum:
              name: python3
              state: latest

          - name: Install PHP
            yum:
              name: php
              state: latest

          - name: php repo
            yum:
              name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
              state: present

          - name: Continue PHP Install
            yum:
              enablerepo: "remi,remi-php80"
              name:
                - php
                - php-common
                - php-cli
                - php-gd
                - php-curl
                - php-mysqlnd
                - php-fpm
                - php-mysqli
                - php-json
              state: latest

          - name: Install Pip2
            shell: curl -sSL https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py

          - name: Install pip2
            command: python get-pip.py "pip < 21.2"

          - name: Install pip3
            command: python3 get-pip.py "pip < 21.2"

          - name: Install MySQL
            pip:
              name: PyMySQL
              state: latest

          - name: Create MariaDB database
            mysql_db: name=wordpress state=present

          - name: Create MariaDB user and pass
            mysql_user:
              name: wordpressuser
              password: Fullsail1
              priv: "*.*:ALL,GRANT"
              host: "localhost"
              state: present

          - name: Flush Privileges
            command: 'mysql -ne "{{item}}"'
            with_items:
              - FLUSH PRIVILEGES

          - name: Restart MariaDB
            service: name=mariadb state=restarted

          - name: Install WordPress from GitHub Repo
            git:
              repo: https://github.com/WordPress/WordPress.git
              dest: /var/www/html
              clone: yes
